# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-04 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abertura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abertura', models.DateTimeField()),
                ('fechamento', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Abertura',
                'verbose_name_plural': 'Aberturas',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(default=0)),
                ('data', models.DateField(auto_now=True)),
                ('mensagem', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Avalia\xe7\xe3o',
                'verbose_name_plural': 'Avalia\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='BairroAtendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frete', models.FloatField(default=0.0)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bairro')),
            ],
            options={
                'verbose_name': 'Bairro de Atendimento',
                'verbose_name_plural': 'Bairros de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=512)),
                ('tipo', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Bandeira',
                'verbose_name_plural': 'Bandeiras',
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('observacao', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=128)),
                ('endereco', models.CharField(max_length=512)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=512)),
                ('senha', models.CharField(max_length=128)),
                ('endereco', models.CharField(max_length=512)),
                ('telefone', models.CharField(max_length=128)),
                ('descricao', models.CharField(max_length=1024)),
                ('nota', models.FloatField(default=0)),
                ('ttl_avaliacoes', models.IntegerField(default=0)),
                ('nota_atual', models.FloatField(default=0.0)),
                ('aceita_cartao', models.BooleanField(default=False)),
                ('aceita_valerefeicao', models.BooleanField(default=False)),
                ('aceita_pagamentoonline', models.BooleanField(default=False)),
                ('status', models.CharField(default='ok', max_length=512)),
                ('porcentagem_repasse', models.FloatField(default=12)),
                ('logotipo', models.CharField(default='sem-logo.jpg', max_length=1024)),
                ('valor_mensalidade', models.FloatField(default=0.0)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=128)),
                ('endereco', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('observacao', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(default=0.0)),
                ('titulo', models.CharField(max_length=512)),
                ('data_pagamento', models.DateField(null=True)),
                ('data_cobranca', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Aguardando Pagamento', max_length=512)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mensalidades', to='core.Empresa')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('tipopagamento', models.CharField(max_length=512)),
                ('obs', models.CharField(max_length=512)),
                ('trocopara', models.FloatField(default=0.0)),
                ('cpfnanota', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('total', models.FloatField()),
                ('status', models.CharField(default='Aguardando Endereco', max_length=512, null=True)),
                ('endereco_entrega', models.CharField(max_length=512)),
                ('complemento_entrega', models.CharField(max_length=512)),
                ('bairro_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bairro')),
                ('cidade_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='core.Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='core.Empresa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('foto', models.CharField(max_length=1024)),
                ('descricao', models.CharField(max_length=1024)),
                ('preco', models.FloatField(null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.Empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=512)),
                ('data_inicio', models.DateField(auto_now=True)),
                ('data_fim', models.DateField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('data_bloqueio', models.DateField(null=True)),
                ('total', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Repasses', to='core.Empresa')),
            ],
            options={
                'verbose_name': 'Cobran\xe7a',
                'verbose_name_plural': 'Cobran\xe7as',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'SubCategorias',
            },
        ),
        migrations.CreateModel(
            name='TipoCozinha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo de Cozinha',
                'verbose_name_plural': 'Tipos de Cozinha',
            },
        ),
        migrations.CreateModel(
            name='TipoPreco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo Pre\xe7o',
                'verbose_name_plural': 'Tipos de Pre\xe7o',
            },
        ),
        migrations.CreateModel(
            name='TipoTempo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo de Tempo M\xe9dio',
                'verbose_name_plural': 'Tipos de Tempo M\xe9dio',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategorias',
            field=models.ManyToManyField(related_name='subcategorias', to='core.SubCategoria'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pagamento', to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoPreco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tempo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoTempo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipocozinha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoCozinha'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.Estado'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='bairroatendimento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BairrosAtendimento', to='core.Empresa'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='core.Cidade'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avaliacoes', to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='abertura',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aberturas', to='core.Empresa'),
        ),
    ]
