# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abertura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abertura', models.DateTimeField()),
                ('fechamento', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Abertura',
                'verbose_name_plural': 'Aberturas',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(default=0)),
                ('data', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avalia\xe7\xe3o',
                'verbose_name_plural': 'Avalia\xe7\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=128)),
                ('endereco', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='TipoCozinha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo de Cozinha',
                'verbose_name_plural': 'Tipos de Cozinha',
            },
        ),
        migrations.CreateModel(
            name='TipoPreco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo Pre\xe7o',
                'verbose_name_plural': 'Tipos de Pre\xe7o',
            },
        ),
        migrations.CreateModel(
            name='TipoTempo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo de Tempo M\xe9dio',
                'verbose_name_plural': 'Tipos de Tempo M\xe9dio',
            },
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='bairros',
            new_name='bairros_atendimento',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='core.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategorias',
            field=models.ManyToManyField(related_name='subcategorias', to='core.SubCategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.Categoria'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avaliado', to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='abertura',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aberturas', to='core.Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoPreco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tempo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoTempo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipocozinha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoCozinha'),
        ),
    ]
