# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
