# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_aceita_pagamentoonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logotipo',
            field=models.CharField(default='sem-logo.jpg', max_length=1024),
        ),
    ]
