# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170604_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='face_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
