# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170315_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='observacao',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
