# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161222_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='bairros',
            new_name='bairros_atendimento',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
