# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-08 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170608_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
