# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
            preserve_default=False,
        ),
    ]
