# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrinho_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro_entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade_entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
