# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170325_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='componente_entrega',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
