# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subcategorias',
            field=models.ManyToManyField(related_name='subcategorias', to='core.SubCategoria'),
        ),
    ]
