# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170614_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcional',
            name='unico',
            field=models.BooleanField(default=True),
        ),
    ]
