# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_subcategorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
