# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_opcional_unico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'verbose_name': 'Op\xe7\xe3o', 'verbose_name_plural': 'Op\xe7\xf5es'},
        ),
    ]
