# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abertura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abertura', models.DateTimeField()),
                ('fechamento', models.DateTimeField(null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aberturas', to='core.Empresa')),
            ],
            options={
                'verbose_name': 'Abertura',
                'verbose_name_plural': 'Aberturas',
            },
        ),
    ]
