# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_status'),
    ]

    operations = [

        migrations.CreateModel(
            name='TipoCozinha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo de Cozinha',
                'verbose_name_plural': 'Tipos de Cozinha',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipocozinha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoCozinha'),
        ),
    ]
