# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170327_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Aguardando Pagamento', max_length=512)),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pagamento',
                'verbose_name_plural': 'Tipos de Pagamentos',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Aguardando Endereco', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pagamento', to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipopagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoPagamento'),
        ),
    ]
