# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170328_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipopagamento',
            field=models.CharField(max_length=512),
        ),
        migrations.DeleteModel(
            name='TipoPagamento',
        ),
    ]
