# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 18:39
from __future__ import unicode_literals
from django.contrib.postgres.operations import CreateExtension

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_abertura'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.AddField(
            model_name='cliente',
            name='geometria',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='empresa',
            name='geometria',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
