# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_opcional_quantitativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='opcionais',
            field=models.ManyToManyField(related_name='opcionais', to='core.Opcional'),
        ),
    ]
