# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170404_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='status',
        ),
    ]
