# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170306_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPreco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo Pre\xe7o',
                'verbose_name_plural': 'Tipos de Pre\xe7o',
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='geometria',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoPreco'),
        ),
    ]
