# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-27 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170620_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcional',
            name='quantitativo',
        ),
        migrations.RemoveField(
            model_name='opcional',
            name='unico',
        ),
        migrations.AddField(
            model_name='opcional',
            name='tipo',
            field=models.CharField(default='U', max_length=8, null=True),
        ),
    ]
