# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pagamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='obs',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
