# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-29 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170627_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcional',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
