# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pagamento_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
