# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTempo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Tipo de Tempo M\xe9dio',
                'verbose_name_plural': 'Tipos de Tempo M\xe9dio',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='tempo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TipoTempo'),
        ),
    ]
