# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_carrinho_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=128),
        ),
    ]
