# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170428_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='trocopara',
            field=models.FloatField(default=0),
        ),
    ]
