# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pagamento_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='custo_beneficio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='embalagem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tempo_entrega',
            field=models.IntegerField(default=0),
        ),
    ]
