# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170428_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='cpfnanota',
            field=models.BooleanField(default=False),
        ),
    ]
