# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171019_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='avaliacao_menuweb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='chegou_hora',
            field=models.BooleanField(default=False),
        ),
    ]
