# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pagamento_cpfnanota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nota_geral',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ttl_avaliacoes',
            field=models.IntegerField(default=0),
        ),
    ]
