# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170503_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nota_geral',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ttl_avaliacoes',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ttl_avaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nota',
            field=models.FloatField(default=0),
        ),
    ]
