# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170503_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='mensagem',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nota_atual',
            field=models.FloatField(default=0),
        ),
    ]
