# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.CharField(default='sem-foto.png', max_length=1024, null=True),
        ),
    ]
