# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170504_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='aceita_cartao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='aceita_valerefeicao',
            field=models.BooleanField(default=False),
        ),
    ]
