# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_empresa_bairros_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(default='', max_length=512),
        ),
    ]
