# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_empresa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(default='ok', max_length=512),
        ),
    ]
