# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170510_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='data_bloqueio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='repasse',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
    ]
