# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170510_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='porcentagem_repasse',
            field=models.FloatField(default=12),
        ),
    ]
